"/local/IMAGES/driving_data_twangcat/tmp/8-13-marin-north-split_0_goldengate_b1-amt_test/output_101.jpeg": (522, 433, 671, 562):-1, (1000, 398, 1276, 844):-1;
"/local/IMAGES/driving_data_twangcat/tmp/8-13-marin-north-split_0_goldengate_b1-amt_test/output_151.jpeg": (638, 447, 773, 564):-1, (366, 456, 480, 546):-1;
"/local/IMAGES/driving_data_twangcat/tmp/8-13-marin-north-split_0_goldengate_b1-amt_test/output_201.jpeg": (535, 449, 623, 527):-1, (625, 473, 651, 495):-1, (640, 475, 673, 501):-1.
